export const NAME: string = process.env.name || ""; // the name of the app
export const CONTRACT_ADDRESS: string = process.env.contract_adress || "";
export const RPC_URL = process.env.rpc_url || ""; // network rpc url
export const NETWORK = process.env.network;
export const WOLF_NFT = process.env.wolf_nft || "";
export const DEER_NFT = process.env.deer_nft || "";
export const BULL_NFT = process.env.bull_nft || "";
export const TEZOS_CONVERTER: number = Number(process.env.tezos_converter);
export const ASSOCIATION_PART = Number(process.env.association_part);
export const WILDIANS_PART = Number(process.env.wildians_part);
export const BUCKET_REGION = process.env.bucket_region;
export const GCPAPIKEY = process.env.gcp_api_key;
export const GCPAUTHDOMAIN = process.env.gcp_auth_domain;
export const GCPDATABASEURL = process.env.gcp_database_url;
export const GCPPROJECTID = process.env.gcp_project_id;
export const GCPSTORAGEBUCKET = process.env.gcp_storage_bucket;
export const GCPMESSAGINGSENDERID = process.env.gcp_messaging_sender_id;
export const GCPAPPID = process.env.gcp_app_id;
export const MEASUREMENTID = process.env.measurement_id;
export const CLARITY_APPID = process.env.clarity_appid;