export const NAME = process.env.name; // the name of the app
export const CONTRACT_ADDRESS = process.env.contract_adress;
export const RPC_URL = process.env.rpc_url; // network rpc url
export const NETWORK = process.env.network;
export const SMART_CONTRACT = process.env.smart_contract;
export const TEZOS_CONVERTER = process.env.tezos_converter;
export const ASSOCIATION_PART = process.env.association_part;
export const WILDIANS_PART = process.env.wildians_part;
export const ADMIN_USERNAME = process.env.admin_username;
export const ADMIN_PASSWORD = process.env.admin_password;
