#!/bin/sh
COMMIT_MSG=$1
echo $1
PATTERN="[[a-zA-Z]*][ ][ a-zA-Z0-9_-]*"

if ! [[ "$COMMIT_MSG" =~ $PATTERN ]]; then
  echo Bad commit message '$COMMIT_MSG'. It must be in the format of '[SOMETHING] message here' 
  exit 1
fi

. "$(dirname "$0")/_/husky.sh"



npm run prettier
yarn test
