name: Development workflow

on:
  # runs on pushes to the main branch
  push:
    branches: [dev]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [dev]

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Prettier
        uses: actions/checkout@v2
      - name: Prettier check
        run: npx prettier 'dapp/**/*.{js,jsx,ts,tsx,html}' --check

  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.17.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          build: yarn run build
          start: yarn run dev
