name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
      uses: actions/checkout@v2
      - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: lts/gallium
        cache: yarn
        cache-dependency-path: lhci/yarn.lock
      - name: run Lighthouse CI
        run: |
          cd lhci
          yarn
          yarn global add @lhci/cli@0.9.0
          lhci autorun --config=./lighthouserc.js