name: Development workflow

on:
    push:
        branches-ignore:
            - "preprod"
            - "main"

jobs:
    prettier:
        runs-on: ubuntu-latest
        steps:
            - name: Prettier
              uses: actions/checkout@v2
            - name: Prettier check
              run:
                  npx prettier --write pages/ && npx prettier
                  'pages/**/*.{js,jsx,ts,tsx,html}' --check

    cypress-run:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node.js environment
              uses: actions/setup-node@v3.5.1
              with:
                  node-version: 16.17.1
            # Install NPM dependencies, cache them correctly
            # and run all Cypress tests
            - name: run cypress tests with chrome
              uses: cypress-io/github-action@v5
              timeout-minutes: 10
              with:
                  browser: chrome
                  configFile: baseUrl=http://localhost:3000
                  build: yarn run build
                  start: yarn run dev
            - uses: actions/upload-artifact@v2
              if: failure()
              with:
                  name: cypress-screenshots
                  path: ./cypress/screenshots
            - uses: actions/upload-artifact@v2
              if: always()
              with:
                  name: cypress-videos
                  path: ./cypress/videos

    lhci:
        if: github.ref == 'refs/heads/dev'
        name: Lighthouse CI
        runs-on: ubuntu-latest
        environment: dev
        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js 16.17.1
              uses: actions/setup-node@v1
              with:
                  node-version: 16.17.1
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  file_name: .env
                  fail_on_empty: true
                  envkey_NETWORK: ${{ secrets.NETWORK }}
                  envkey_RPC_URL: ${{ secrets.RPC_URL }}
                  envkey_WOLF_NFT: ${{ secrets.WOLF_NFT }}
                  envkey_DEER_NFT: ${{ secrets.DEER_NFT }}
                  envkey_BULL_NFT: ${{ secrets.BULL_NFT }}
                  envkey_TEZOS_CONVERTER: ${{ secrets.TEZOS_CONVERTER }}
                  envkey_WILDIANS_PART: ${{ secrets.WILDIANS_PART }}
                  envkey_ASSOCIATION_PART: ${{ secrets.ASSOCIATION_PART }}
                  envkey_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
                  envkey_CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
                  envkey_GCPAPIKEY: ${{ secrets.GCPAPIKEY }}
                  envkey_GCPAPPID: ${{ secrets.GCPAPPID }}
                  envkey_GCPAUTHDOMAIN: ${{ secrets.GCPAUTHDOMAIN }}
                  envkey_GCPDATABASEURL: ${{ secrets.GCPDATABASEURL }}
                  envkey_GCPMESSAGINGSENDERID:
                      ${{ secrets.GCPMESSAGINGSENDERID }}
                  envkey_GCPPROJECTID: ${{ secrets.GCPPROJECTID }}
                  envkey_GCPSTORAGEBUCKET: ${{ secrets.GCPSTORAGEBUCKET }}
                  envkey_BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
                  envkey_NAME: ${{ secrets.NAME }}
            - name: Install
              run: |
                  npm install -g yarn
            - run: yarn install --frozen-lockfile
            - name: run Lighthouse CI
              run: |
                  yarn global add @lhci/cli@0.3.x
                  yarn run build
                  lhci autorun

    deploy-app:
        if: github.event_name == 'push' && github.ref == 'refs/heads/dev'
        environment: dev
        runs-on: ubuntu-latest
        needs:
            - cypress-run
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 16.17.1
            - name: Make envfile
              uses: SpicyPizza/create-envfile@v1.3
              with:
                  file_name: .env
                  fail_on_empty: true
                  envkey_NETWORK: ${{ secrets.NETWORK }}
                  envkey_RPC_URL: ${{ secrets.RPC_URL }}
                  envkey_WOLF_NFT: ${{ secrets.WOLF_NFT }}
                  envkey_DEER_NFT: ${{ secrets.DEER_NFT }}
                  envkey_BULL_NFT: ${{ secrets.BULL_NFT }}
                  envkey_TEZOS_CONVERTER: ${{ secrets.TEZOS_CONVERTER }}
                  envkey_WILDIANS_PART: ${{ secrets.WILDIANS_PART }}
                  envkey_ASSOCIATION_PART: ${{ secrets.ASSOCIATION_PART }}
                  envkey_CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
                  envkey_GCPAPIKEY: ${{ secrets.GCPAPIKEY }}
                  envkey_GCPAPPID: ${{ secrets.GCPAPPID }}
                  envkey_GCPAUTHDOMAIN: ${{ secrets.GCPAUTHDOMAIN }}
                  envkey_GCPDATABASEURL: ${{ secrets.GCPDATABASEURL }}
                  envkey_GCPMESSAGINGSENDERID:
                      ${{ secrets.GCPMESSAGINGSENDERID }}
                  envkey_GCPPROJECTID: ${{ secrets.GCPPROJECTID }}
                  envkey_GCPSTORAGEBUCKET: ${{ secrets.GCPSTORAGEBUCKET }}
                  envkey_BUCKET_REGION: ${{ secrets.BUCKET_REGION }}
                  envkey_NAME: ${{ secrets.NAME }}
            - run: npm install -g yarn
            - run: yarn install --frozen-lockfile
            - run: yarn build

            - name: Netlify deploy
              uses: jsmrcaga/action-netlify-deploy@v2.0.0
              with:
                  NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
                  NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
                  NETLIFY_DEPLOY_TO_PROD: true
                  build_directory: out/
