name: preprod workflow

on:
  # runs on pushes to the main branch
  push:
    branches: [feature/cd-gcp]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [preprod]

jobs:
  # cypress-run:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2
  #     # Install NPM dependencies, cache them correctly
  #     # and run all Cypress tests
  #     - name: run cypress tests with firefox
  #       uses: cypress-io/github-action@v4
  #       timeout-minutes: 10
  #       with:
  #         start: yarn run dev

  deploy-app:
    runs-on: ubuntu-latest
    needs:
      - cypress-run
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: yarn build
      
      - name: check
        run: ls

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ./out/
          project_id: "${{ secrets.GCP_PROJECT }}"
          destination: "${{ secrets.BUCKET_NAME }}"
