name: preprod workflow

on:
  # runs on pushes to the main branch
  push:
    branches: [preprod]
  # also runs inside pull requests that target the main branch
  pull_request:
    branches: [preprod]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.17.1
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: run cypress tests with firefox
        uses: cypress-io/github-action@v4
        timeout-minutes: 10
        with:
          start: yarn run dev

  status-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check status of the web app
        run: curl -I  https://storage.googleapis.com/aerobic-guide-364710-website/index.html | grep "HTTP/2 200"

  deploy-app:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs:
      - cypress-run
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ./out/
          project_id: "${{ secrets.GCP_PROJECT }}"
          destination: "${{ secrets.BUCKET_NAME }}"
          parent: false
