name: preprod workflow

on:
  # runs on pushes to the main branch
  push:
    branches: [preprod]


jobs:
  deploy-app:
    if: github.event_name == 'push'
    environment: preprod
    runs-on: ubuntu-latest
    needs:
      - cypress-run
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16.17.1
      - run: npm install -g yarn
      - run: yarn install --frozen-lockfile
      - run: yarn build

      - id: "auth"
        uses: "google-github-actions/auth@v0"
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}"

      - id: "upload-folder"
        uses: "google-github-actions/upload-cloud-storage@v0"
        with:
          path: ./out/
          project_id: "${{ secrets.GCP_PROJECT }}"
          destination: "${{ secrets.BUCKET_NAME }}"
          parent: false
